# Generated by Django 3.1.7 on 2021-03-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('middlename', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=30)),
                ('userP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyAPI.userp')),
            ],
        ),
    ]
