# Generated by Django 3.1.7 on 2021-03-07 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user_id',
            new_name='user',
        ),
    ]
